### PR TITLE
delete simple provider package, use gradle dependency

### PR DESCRIPTION
**Pull request by ChrisDolge**
Second try :laughing:

I have deleted the simpleprovider package. Because the guys from Triple-T add a gradle dependency. So we can use this instead of the package. I think it looks a bit cleaner :)

And it is better for updating a newer version.

### CODE REVIEW

**Comment by francisdb** [comment]
+1 any replacement for `mapareas`?

**Comment by ChrisDolge** [comment]
Sorry ,

there are no gradle dependency for mapareas

**Comment by francisdb** [comment]
well mapareas seems to broken with the latest google maps... see #19 and maybe #16
Do you also have these issues?

**Comment by francisdb** [comment]
So who should push the merge button :)

**Comment by ChrisDolge** [comment]
I think @kimar  that is your part :smirk:

**Comment by kimar** [comment]
As we have no tests in place I'm sure this is a good idea :-D If everything works let's give it a go :+1:

**Pull request merged**
