### PR TITLE
Add Crashlytics

### PR DESCRIPTION
**Pull request by chrissd23**
With secret api key :)

### CODE REVIEW

**Comment by kimar** [comment]
Ok, I've added the two env vars to Travis now, btw. why are they named "DEMO" ? Also they're not specifically tied to Crashlytics but Fabric wide if I'm correct, right? Maybe we could just rename them "FABRIC_API_KEY" and "FABRIC_API_SECRET"? If the build is green I'll export those too in case you want to change them...

**Comment by kimar** [comment]
I wasn't sure if I still need to export those prefixes so I exported both versions but the build still fails and complains about the missing variables. Do you have any idea on how to solve this @chrissd23 ?

Do you have access to Travis? https://travis-ci.org/LocativeHQ/android-app/settings

screen shot 2016-04-23 at 6 45 03 pm

**Comment by chrissd23** [comment]
Hi @kimar , sorry I had a hockey tournament this weekend and I wasn't at home :grin: 

Yes now I have access rights to travis. 👍 

I'll check this later on that day. Can I build my PR manually on travis ? @kimar

**Comment by chrissd23** [comment]
Hi guys, 

I was wondering to add a second flag in the build.gradle file where a developer can set a boolean value. So they can decide whether they like it or not to use crashlytics. Because currently we force developers to use crashlytics otherwise the build failed. :flushed:

What do you think @kimar @francisdb ...?

**Comment by francisdb** [comment]
I personally see no use to enable it for development.
But I don't mind configuring it in my environment
http://stackoverflow.com/questions/16986753/how-to-disable-crashlytics-while-developing

**Comment by kimar** [comment]
@chrissd23 I would probably disable it for development...

**Comment by kimar** [comment]
@chrissd23 regarding manually re-building @ travis, yeah that's totally feasible. there is a button which looks like a reload button. I've just triggered a rebuild for this branch...

**Pull request closed without merging**
