### PR TITLE
Missing Runtime Permissions for Android Version 6.0 

### PR DESCRIPTION
**Pull request by robertbaptiste**
On Android M devices, permissions need to be asked at runtime.
Moreover, I add a  small cleanup on BaseActivity and LocativeApplication.

### CODE REVIEW

**Comment by kimar** [comment]
@robertbaptiste awesome, thank you! I wonder why Travis is failing to build though, we've got another PR open which also fails so I'm not sure what the exact reason is, would you mind taking a look into this? Apart from that great work and really appreciate to get this merged asap.

**Comment by robertbaptiste** [comment]
Hi @kimar,

Thanks ! 

The issue is because I updated the gradle version to gradle-2.1.0-beta1. Travis didn't manage to get it, I will try to fix it.

**Comment by robertbaptiste** [comment]
Bingo !

The build was failing for 2 reasons:
1. I was trying to use an experimental version of gradle which is not published in the repo used by Travis: https://repo1.maven.org/maven2/com/android/tools/build/gradle/
2. You have 105 lint issues. To avoid a failed build I was forced to add:
    ```
lintOptions {
        abortOnError false
    }
```
to build.gradle. This is not really a good thing :/ and all these lint issues must be handle in another ticket. Do you want an issue for that ?

**Comment by kimar** [comment]
Awesome! @robertbaptiste yeah please raise an issue for this! Thanks for contributing, going to merge this now!

**Comment by robertbaptiste** [comment]
@kimar Done: https://github.com/LocativeHQ/android-app/issues/43

**Pull request merged**
