### PR TITLE
redesign setting activity

### PR DESCRIPTION
**Pull request by chrissd23**
Hi, 

I did some little changes. 

screenshot_20151209-224352

What do you think @kimar @francisdb ? :blush:

### CODE REVIEW

**Comment by francisdb** [comment]
I like the better splitting of sections!

some remarks

more material design buttons please
The POST / GET button should be dropdown or radio button (toggle buttons docs mention at least 3 options)
http://www.google.be/design/spec/components/buttons.html#buttons-dropdown-buttons
http://www.google.be/design/spec/components/buttons.html#buttons-toggle-buttons
Http basic auth is not aligned

**Comment by kimar** [comment]
Nice @chrissd23, looks awesome. Could you change the "My Geofancy Account" wording to "My Locative Account"? Apart from that :+1:

**Comment by chrissd23** [comment]
I will change it :wink:

**Comment by francisdb** [comment]
The account form + main http url seems to have different styling for the input fields, thicker line, more right aligned, other font.
Also username and password are different on the global section, less spacing with line on the password field and different font?

**Comment by francisdb** [comment]
The global http settings user name field looks the best to me compared to the other versions

**Comment by francisdb** [comment]
@chrissd23 I guess we can just merge this and fix things afterwards?

**Comment by chrissd23** [comment]
@francisdb Yes , we can do that. Sorry I was recently very busy at work. I hope it will get better soon :)

**Comment by francisdb** [comment]
Same here, we will have some interns soon and I hope they will be able to integrate locative. Should make me test/use/dev locative more

**Comment by kimar** [comment]
:-D I've also been pretty busy with other project recently, guys nobody has an obligation to work on that stuff, most important thing is having fun with it :+1:

**Pull request merged**
