### PR TITLE
Rename package and applicationId to io.locative.app

### PR DESCRIPTION
**Pull request by ChrisDolge**
Hi, 

I rename the package to io.locative.app ;) 

I think that's a clean name :blush:   :+1:

### CODE REVIEW

**Comment by kimar** [comment]
Looks good to me :+1: @francisdb any comments on this?

**Comment by francisdb** [comment]
LGTM, I'll press the button

**Comment by francisdb** [comment]
@kimar should we keep working with push requests?

**Comment by kimar** [comment]
In general I'd say yes, this ensure we all stay on the same page, what do you say?

**Comment by ChrisDolge** [comment]
I agree with @kimar

**Comment by francisdb** [comment]
Ok, will try to keep that in mind

**Comment by kimar** [comment]
No worries, I think if it's just minor things, like updating the README etc, we don't need to do pull requests.

**Pull request merged**
